//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritingPad
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotePad
    {
        public int NotePadId { get; set; }
        public string Title { get; set; }
        public string Explanation { get; set; }
        public int AppUserId { get; set; }
        public string NoteUrl { get; set; }
        public string FilePath { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
